spring.application.name=User Service
server.port=8081

# Налаштування бази даних H2 як бази даних в пам'яті
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Відображення SQL-запитів в консолі
spring.jpa.show-sql=true