spring.application.name=User Service
server.port=8081

# Налаштування бази даних H2 як бази даних в пам'яті
spring.datasource.url=jdbc:postgresql://localhost:5432/userdb
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
# Відображення SQL-запитів в консолі
spring.jpa.show-sql=true

# ==== Zipkin Configuration ====
spring.zipkin.base-url=http://localhost:9411
spring.zipkin.enabled=true
# ==== Tracing Configuration ====
management.tracing.sampling.probability=1.0
# ==== Log Trace IDs ====
logging.pattern.level=%5p [traceId=%X{traceId}, spanId=%X{spanId}]
# ==== Actuator and Prometheus Metrics ====
management.endpoints.web.base-path=/management
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=beans
management.endpoint.health.show-details=always
management.endpoint.env.show-values=when_authorized
# Micrometer settings
management.metrics.export.prometheus.enabled=true